apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: client-go-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: client-go-role
  apiGroup: rbac.authorization.k8s.io